version: "3.9"
services:
  hadoop:
    build: ./hadoop
    container_name: hadoop-master
    hostname: namenode
    ports:
      - "50070:50070" # NameNode WebUI
      - "8088:8088"   # ResourceManager WebUI
      - "9000:9000"   # HDFS NameNode
    networks:
      - hadoop-network
    environment:
      HDFS_NAMENODE_USER: root
      HDFS_DATANODE_USER: root
      HDFS_SECONDARYNAMENODE_USER: root
      YARN_RESOURCEMANAGER_USER: root
      YARN_NODEMANAGER_USER: root

networks:
  hadoop-network:
    driver: bridge
